### ISSUE TITLE
Consider including urbit keyfile generation

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit-key-generation#101]
A common use case for networking keys generated by this lib is creating a `.key` file for booting an urbit with. We might want to consider including logic for creating that file directly in this lib, instead of asking users to roll their own.

There's a case to be made that this is out of scope, but this comes up with some frequency, so just filing for the record at the very least.

**Comment by jtobin** [comment]
I was recently asked about this, so can probably take a look at it.
