### ISSUE TITLE
keygen-js build status in README is broken

### ISSUE THREAD

**Issue by msutherl** [urbit/urbit-key-generation#69]
<img width="198" alt="Screenshot 2019-06-13 12 34 42" src="https://user-images.githubusercontent.com/31774/59462078-b70bce00-8dd7-11e9-8f31-c91c31de7b8d.png">

https://travis-ci.org/urbit/keygen-js

**Comment by jtobin** [comment]
Nice catch bru.  I must have missed this one when renaming.

**Comment by jtobin** [comment]
Fixed in 7e4a9049002560149e80335fe21a65d6a4ce4554.
