### ISSUE TITLE
Should this test ever pass?

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/urbit-key-generation#73]
This equality check is not making sense to me. Note we are comparing the wallet object to a part of the reference wallet.  
```js
wallet = await kg.generateOwnershipWallet(config)
expected = objectFromFile('./test/assets/wallet1.json')

expect(lodash.isEqual(wallet, expected.ownership)).to.equal(true)
```

**Comment by g-a-v-i-n** [comment]
Any thoughts @Fang-

**Comment by g-a-v-i-n** [comment]
resolved

**Comment by Fang-** [comment]
![image](https://user-images.githubusercontent.com/3829764/62143350-268a3e00-b2f0-11e9-994e-715f8a791cfb.png)
